#!/usr/bin/env bash
# runs nginx as nginx user

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
chown www-data:www-data /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
pkill apache2
sudo -u www-data service nginx start

