#!/usr/bin/env bash
# runs nginx as www-data

pkill apache2
chown www-data:www-data /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u www-data service nginx start

