#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

#Installation
sudo apt-get update
sudo apt-get install ufw

#Enable ufw 
sudo ufw enable

#Allow SSH (port 22), HTTPS (port 443), and HTTP (port 80):
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

#Block all incoming traffic by default:
sudo ufw default deny incoming

#Allow all outgoing traffic by default:
sudo ufw default allow outgoing

#Check the rules to make sure they are configured correctly:
sudo ufw status
