#!/bin/bash

# Update the system
sudo apt update
sudo apt upgrade -y

# Install HAProxy if not already installed
if ! command -v haproxy &>/dev/null; then
    sudo apt install -y haproxy
fi

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    option http-server-close
    option forwardfor
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_frontend
    bind *:80
    mode http
    default_backend http_backend

backend http_backend
    mode http
    balance roundrobin
    server 673187647-web-01 54.85.25.198:80 check
    server 673187647-web-02 50.19.132.15:80 check
EOF

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy

# Verify the HAProxy status
sudo systemctl status haproxy

# Verify the hostname
hostname

